<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>LivingCalradia</AssemblyName>
		<RootNamespace>LivingCalradia</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Reference Include="TaleWorlds.CampaignSystem">
	    <HintPath>F:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
	  </Reference>
	  <Reference Include="TaleWorlds.Core">
	    <HintPath>F:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
	  </Reference>
	  <Reference Include="TaleWorlds.Library">
	    <HintPath>F:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
	  </Reference>
	  <Reference Include="TaleWorlds.Localization">
	    <HintPath>F:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
	  </Reference>
	  <Reference Include="TaleWorlds.MountAndBlade">
	    <HintPath>F:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
	  </Reference>
	  <Reference Include="TaleWorlds.ObjectSystem">
	    <HintPath>F:\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>